---
- name: Mise à jour Oracle Linux 7/8/9 avec gestion LVM, Zabbix, Grafana, Teams, NFS
  hosts: all
  become: yes
  vars:
    nfs_mount_path: "{{ nfs_mount_point }}/{{ ansible_hostname }}/{{ ansible_date_time.date }}"
    zabbix_host_name: "{{ ansible_hostname }}"
    zabbix_update_status_key: "oracle.update.status"
    zabbix_update_error_key: "oracle.update.error"
    snapshot_list: []

  tasks:
    - name: Déterminer la version d'Oracle Linux
      ansible.builtin.setup:
        gather_subset: "!all"
        filter: ansible_distribution_version

    - name: Vérifier que le système est bien Oracle Linux Server
      assert:
        that:
          - ansible_distribution == "OracleLinux"
        fail_msg: "Ce système n'est pas Oracle Linux Server. Actuel : {{ ansible_distribution }} {{ ansible_distribution_version }}. Seules les versions Oracle Linux 7, 8, 9 sont prises en charge."

    - name: Extraire la version majeure
      set_fact:
        ol_version: "{{ ansible_distribution_version.split('.')[0] | int }}"

    - name: Afficher les faits du système
      debug:
        msg: "Distribution: {{ ansible_distribution }} | Version: {{ ansible_distribution_version }} | Version majeure: {{ ansible_distribution_version.split('.')[0] | int }} | ol_version: {{ ol_version }}"

    - name: Inclure les tâches spécifiques à la version
      include_tasks: "tasks/ol{{ ol_version }}.yml"
      when: ol_version == '7' or ol_version == '8' or ol_version == '9'

    - name: Si version non supportée, échouer
      fail:
        msg: "Version Oracle Linux {{ ansible_distribution_version }} non supportée. Seules les versions 7, 8 et 9 sont prises en charge."
      when: ol_version == '7' or ol_version == '8' or ol_version == '9'

    # --- Tâches communes après la mise à jour ---
    - name: Vérifier si un redémarrage est requis
      shell: "{{ reboot_command }}"
      register: reboot_check
      changed_when: false

    - name: Stocker le résultat du redémarrage requis
      set_fact:
        reboot_required: "{{ reboot_check.stdout == 'yes' }}"

    - name: Redémarrer le système si nécessaire
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 10
      when: reboot_required

    - name: Nettoyer le cache
      include_tasks: "tasks/cleanup_cache.yml"

    - name: Sauvegarder la liste des paquets après mise à jour
      command: rpm -qa --qf '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n'
      register: installed_packages_after
      changed_when: false

    - name: Sauvegarder la liste des paquets après mise à jour
      copy:
        content: "{{ installed_packages_after.stdout }}"
        dest: "{{ backup_dir }}/packages_after_update.txt"
        mode: '0644'

    - name: Générer un rapport de mise à jour
      template:
        src: update_report.j2
        dest: "{{ backup_dir }}/update_report.txt"
        mode: '0644'
      vars:
        hostname: "{{ ansible_hostname }}"
        date: "{{ ansible_date_time.iso8601 }}"
        packages_updated: "{{ yum_update_result.changed }}"
        reboot_required: "{{ reboot_required }}"
        packages_before: "{{ installed_packages_before.stdout_lines | length }}"
        packages_after: "{{ installed_packages_after.stdout_lines | length }}"
        excluded_packages: "{{ excluded_packages }}"
        lvm_snapshot: "{{ snapshot_name }}"

    - name: Copier le rapport sur le serveur NFS
      copy:
        src: "{{ backup_dir }}/update_report.txt"
        dest: "{{ nfs_mount_path }}/update_report_{{ ansible_date_time.iso8601_basic_short }}.txt"
        remote_src: no
        mode: '0644'
      when: nfs_mount_result.mounted

    - name: Copier les logs de sauvegarde sur NFS
      copy:
        src: "{{ backup_dir }}/packages_before_update.txt"
        dest: "{{ nfs_mount_path }}/packages_before_{{ ansible_date_time.iso8601_basic_short }}.txt"
        remote_src: no
        mode: '0644'
      when: nfs_mount_result.mounted

    - name: Copier les logs après mise à jour sur NFS
      copy:
        src: "{{ backup_dir }}/packages_after_update.txt"
        dest: "{{ nfs_mount_path }}/packages_after_{{ ansible_date_time.iso8601_basic_short }}.txt"
        remote_src: no
        mode: '0644'
      when: nfs_mount_result.mounted

    # --- Inclusion conditionnelle des modules ---
    - name: Inclure les tâches Teams si activé
      include_tasks: "tasks/teams.yml"
      when: enable_teams | bool

    - name: Inclure les tâches Zabbix si activé
      include_tasks: "tasks/zabbix.yml"
      when: enable_zabbix | bool

    - name: Inclure les tâches Grafana si activé
      include_tasks: "tasks/grafana.yml"
      when: enable_grafana | bool

    - name: Inclure les tâches mail si activé
      include_tasks: "tasks/mail.yml"
      when: enable_mail | bool

    # --- Rollback automatique si mise à jour échouée ---
    - name: Rollback automatique si mise à jour échouée
      block:
        - name: Restaurer depuis le snapshot LVM
          shell: |
            lvconvert --merge /dev/{{ lvm_vg }}/{{ snapshot_name }}
            echo "Snapshot {{ snapshot_name }} restauré."
          register: rollback_result
          args:
            executable: /bin/bash

        - name: Redémarrer après rollback
          reboot:
            reboot_timeout: 300
            pre_reboot_delay: 10

        - name: Inclure les tâches teams_error si activé
          include_tasks: "tasks/teams_error.yml"
          when: enable_teams | bool

        - name: Inclure les tâches zabbix_error si activé
          include_tasks: "tasks/zabbix_error.yml"
          when: enable_zabbix | bool

        - name: Nettoyer le snapshot après rollback
          lvol:
            vg: "{{ lvm_vg }}"
            lv: "{{ snapshot_name }}"
            state: absent
          register: snapshot_cleanup_rollback
          ignore_errors: yes

        - name: Journaliser le rollback
          copy:
            content: |
              Rollback effectué sur {{ ansible_hostname }} le {{ ansible_date_time.iso8601 }}
              Snapshot restauré : {{ snapshot_name }}
              Statut : {{ 'réussi' if snapshot_cleanup_rollback is not failed else 'échec' }}
            dest: "{{ backup_dir }}/rollback_log.txt"
            mode: '0644'

      rescue:
        - name: Log d'erreur de rollback
          debug:
            msg: "Échec du rollback LVM sur {{ ansible_hostname }}. Vérifiez manuellement le snapshot : {{ snapshot_name }}"

    # --- Nettoyage des snapshots obsolètes (si mise à jour réussie) ---
    - name: Nettoyer les snapshots obsolètes (si mise à jour réussie)
      block:
        - name: Lister tous les snapshots du VG
          shell: lvs --noheadings -o lv_name,lv_size,lv_attr --select "lv_name=~^{{ snapshot_prefix }}" {{ lvm_vg }}
          register: lvm_snapshots_list
          changed_when: false

        - name: Extraire les noms des snapshots
          set_fact:
            snapshot_list: "{{ lvm_snapshots_list.stdout_lines | map('split') | map('first') | list }}"

        - name: Nettoyer les snapshots plus anciens que {{ snapshot_retention_days }} jours
          lvol:
            vg: "{{ lvm_vg }}"
            lv: "{{ item }}"
            state: absent
          loop: "{{ snapshot_list }}"
          when: item != snapshot_name and item is defined and item | regex_replace(snapshot_prefix, '') | to_datetime < (ansible_date_time.iso8601 | to_datetime - (snapshot_retention_days * 24 * 3600) | to_datetime)
          register: snapshot_cleanup_old

        - name: Journaliser le nettoyage des snapshots
          copy:
            content: |
              Nettoyage des snapshots obsolètes sur {{ ansible_hostname }} le {{ ansible_date_time.iso8601 }}
              Snapshots supprimés : {{ snapshot_cleanup_old.results | selectattr('changed', 'defined') | selectattr('changed', '==', True) | map(attribute='item') | list | join(', ') }}
            dest: "{{ backup_dir }}/snapshot_cleanup_log.txt"
            mode: '0644'

      when: yum_update_result.changed or not yum_update_result.failed

    - name: Nettoyer le snapshot actuel (si mise à jour réussie)
      lvol:
        vg: "{{ lvm_vg }}"
        lv: "{{ snapshot_name }}"
        state: absent
      register: snapshot_cleanup_current
      when: not yum_update_result.failed

    - name: Journaliser la suppression du snapshot courant
      copy:
        content: |
          Snapshot {{ snapshot_name }} supprimé sur {{ ansible_hostname }} le {{ ansible_date_time.iso8601 }}
          Statut : {{ 'réussi' if snapshot_cleanup_current is not failed else 'échec' }}
        dest: "{{ backup_dir }}/snapshot_cleanup_current_log.txt"
        mode: '0644'
      when: not yum_update_result.failed